package edu.baylor.cs.se.hibernate;// Generated by Selenium IDE

import org.junit.jupiter.api.*;


import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class SeleniumTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    //Before your test runs, it's sets
    @BeforeEach
    public void setUp() {

        //Setup chromedriver
        System.setProperty("webdriver.chrome.driver", "chromedriver");
//     //If you don't want to see all the created drivers running while you test them
//    //------headless test runs--------
//        ChromeOptions options = new ChromeOptions();
//        options.addArguments("--headless");
//        driver = new ChromeDriver(options);
//    //--------------------------------
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    //After your test runs, it quits
    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    //First test
    @Test
    public void shouldAddName1() {
        test1("test1");
    }

    public void test1(String suffix) {
        driver.get("http://localhost:4200/register");
        driver.manage().window().setSize(new Dimension(1512, 863));
        driver.findElement(By.id("name")).click();
        driver.findElement(By.id("name")).sendKeys("name" + i + " " + suffix);
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > #name")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > #name")).sendKeys("author" + i + " " + suffix);
        driver.findElement(By.id("txt")).click();
        driver.findElement(By.id("txt")).sendKeys("20");
        {
            WebElement element = driver.findElement(By.name("submit_reg"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.name("submit_reg")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();
        driver.findElement(By.cssSelector("div > .btn")).click();
    }

    //Second test: This is a parallel test where it is also adding name
    @Test
    public void shouldAddName2() {
        test1("test2");
    }


}
